services:
  db:
    image: postgis/postgis:17-3.5
    restart: always  # Restart the database if it crashes
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onehealth_db  # Default database to create
    ports:
      - "5432:5432"  # Map PostgreSQL port to the host "host_port:container_port"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres_data:  # Named volume for database persistence
