services:
  db:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: onehealth-postgres-container
    restart: always  # Restart the database if it crashes
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Map PostgreSQL port to the host "host_port:container_port"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
      - ./_scripts/sql/initial_db_sandbox_setup.sql:/docker-entrypoint-initdb.d/init.sql  # Run initial SQL script

volumes:
  postgres_data:  # Named volume for database persistence
