site_name: OneHealth Project
site_url: https://ssciwr.github.io/onehealth-db/
theme:
  name: material

nav:
  - Home: index.md
  - Sample Page: sample.md

plugins:
  - search
  - include-markdown
  - glightbox

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
