site_name: One Health Platform
site_url: https://ssciwr.github.io/onehealth-db/
theme:
  name: material
  #logo: path/to/file.png

nav:
  - Home: index.md
  - About: about.md
  - Data: data.md
  - Data Lake & Database: datalake_database.md
  - Contact: contact.md

plugins:
  - search
  - include-markdown
  - glightbox

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
