site_name: One Health Platform
site_url: https://ssciwr.github.io/onehealth-db/
repo_url: https://github.com/ssciwr/onehealth-db
repo_name: "ssciwr/onehealth-db"
theme:
  name: material
  #logo: path/to/file.png

nav:
  - Home: index.md
  - About: about.md
  - Data: data.md
  - Data Lake & Database: datalake_database.md
  - References:
    - Package Modules: reference/
    - Demonstration Notebooks:
      - data_pipeline.ipynb: source/notebooks/data_pipeline.ipynb
      - insert_data.ipynb: source/notebooks/insert_data.ipynb
  - Contact: contact.md

extra_css:
  - source/stylesheets/md4py.css

plugins:
  - search
  - include-markdown
  - glightbox
  - mkdocs-jupyter:
      execute: false
      ignore_h1_titles: true
  - gen-files:
      scripts:
        - _scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_symbol_type_heading: true
            show_root_heading: false

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - pymdownx.blocks.caption

extra_javascript:
  - source/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - source/javascripts/md4py.js
