name: CI Check
on: [push, pull_request, workflow_dispatch]
jobs:
  clean-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11', '3.12']
    services:
      docker:
        image: docker:24.0.0
        options: --privileged
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Getting repository
      uses: actions/checkout@v4

    - name: Install dependencies and package
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Install pytest
      run: |
        pip install pytest pytest-cov

    - name: Create .cdsapirc file
      run: |
        echo "url: https://cds.climate.copernicus.eu/api" >> ~/.cdsapirc
        echo "key: ${{ secrets.CDSAPI_KEY }}" >> ~/.cdsapirc

    - name: Execute PyTest
      env:
          DOCKER_HOST: unix:///var/run/docker.sock
      run: python -m pytest -svv --cov=onehealth_db --cov-report=xml:onehealth_db/coverage_re/coverage.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./onehealth_db/coverage_re/